language: node_js
node_js:
- '0.12'
sudo: false
env:
- TEST_SUITE=units
- TEST_SUITE=integration
before_install:
- npm run install-bats
before_script:
- npm run compile
script:
- npm run test-$TEST_SUITE
after_success:
- npm run codecov
deploy:
  provider: npm
  email: git@jwr.vc
  api_key:
    secure: K/+dVjtCqesr5E5EMZo/qBdKlWwPpZ60yp1GtKoAhSZUtL4VY4A8LOJmcSeIeYvsPkK8PRSCyb2FTDfSTYEO4dWVfNPoLxWp7U48iIiHSfLdNixfTiBHyjdKdP/6oCz3TNfb9upPUb1lcb5h+rM2KJgCLT6s30Vbajka6STeDCs=
  on:
    tags: true
    repo: jamesramsay/hercule
