language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
  - test/modules
before_install:
- npm run install-bats
after_success:
- npm run codecov
deploy:
  provider: npm
  email: git@jwr.vc
  api_key:
    secure: K/+dVjtCqesr5E5EMZo/qBdKlWwPpZ60yp1GtKoAhSZUtL4VY4A8LOJmcSeIeYvsPkK8PRSCyb2FTDfSTYEO4dWVfNPoLxWp7U48iIiHSfLdNixfTiBHyjdKdP/6oCz3TNfb9upPUb1lcb5h+rM2KJgCLT6s30Vbajka6STeDCs=
  on:
    tags: true
    repo: jamesramsay/hercule
